FROM ros:humble-ros-base

RUN rm -f /etc/apt/sources.list.d/ros2-latest.list && \
    apt update && \
    apt install -y curl gnupg lsb-release vim python3-pip && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor -o /usr/share/keyrings/ros2-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/ros2-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list && \
    apt update && \
    apt install -y ros-humble-sensor-msgs-py && \
    pip3 install tqdm pandas pyarrow

CMD ["bash"]
